#!/usr/bin/env gawk -f
# Calculates balances of accounts from preprocessed postings
# Usage:
# postings | rg "$pattern" | balance

BEGIN {
    OFS = "\t";
}

{
    balances[$3] += +$2
    next
}

END {
    # Propagate amounts to parents
    for (account in balances) {
        parent = account
        sub(":.*$", "", parent)
        if (parent == account) break
        balances[parent] += +balances[account]
        total += balances[account]
    }

    # print account balances sorted
    PROCINFO["sorted_in"] = "@ind_str_asc";
    for (account in balances) {
        printf("%12.2f %s\n", balances[account], account)
    }
    # Print total
    printf("%12.2f total\n", total);
}
