#!/usr/bin/env awk -f
# Converts from ledger format to pta transaction format

BEGIN {
    FS="[ \t]+"
    OFS=" "
    balance = 0
}

# transaction lines: Account Value
/^[ \t]+[A-Za-z]/ {
    # empty account amount currency comment
    # ->
    # date amount currency:account rest 

    if ($3) {
        balance -= +$3
        curr = $4
        amount = $3
        if (curr == ";") curr = ""
        if (curr) curr = curr ":"
        print "", amount, curr $2
    } else {
        print realdate, balance, curr $2
        balance = 0
    }
    next
}

# trasaction header: Date Description
/^[0-9]{4}-[0-9]{2}-[0-9]{2}/ {
    split($1, dates, "=")
    date = dates[1]
    realdate = dates[2]
    $1 = date
    print ""
    print date, tags
    $1 = ""
    tags = $0
    balance = 0
    next
}
