#!/bin/bash
# sort transactions without processing them
awk '
BEGIN {
    OFS = "\t"
    prefix = "0"
}

/^alias / {
    prefix = "0"
    print prefix, $0
    next
}

/[0-9]{4}-[0-9]{2}(-[0-9]{2})? / {
    prefix = $1
}

{
    print prefix, $0
}
' | sort -k 1,1 -s | awk -F '\t' '{print $2}'
